lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: 3600

    token_extractors:
        cookie:
            enabled: true
            name: BEARER

    set_cookies:
        BEARER:
            lifetime: null
            samesite: 'none'
            path: '/'
            domain: null
            secure: true
            httpOnly: true
    
    # token extraction settings
    # token_extractors:
    #     split_cookie:
    #         enabled: true
    #         cookies:
    #             - jwt_hp
    #             - jwt_s

    # set_cookies:
    #     jwt_hp:
    #         lifetime: null
    #         samesite: strict
    #         path: /
    #         domain: null
    #         httpOnly: false
    #         split:
    #             - header
    #             - payload

    #     jwt_s:
    #         lifetime: 0
    #         samesite: strict
    #         path: /
    #         domain: null
    #         httpOnly: true
    #         split:
    #             - signature



